title: Castaner
description: Castaner
theme: just-the-docs

url: https://espadrillesbanyoles-lautaroespinosa.github.io/docs/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
